development:
  adapter: mysql2
  encoding: utf8
  database: dev_glucose_db
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: test_glucose_db
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  socket: /tmp/mysql.sock
